# Matriz formal de atributos de calidad — priorizada y justificada

Esta matriz cruza los **drivers de negocio** y **drivers de calidad** definidos para CookSmart con los atributos de calidad trabajados en `Docs/02-Escenarios-de-calidad.md`, y los prioriza con base en evidencia real del sistema construido (no solo en teoría de arquitectura).

>  el equipo ya estableció una priorización formal de 5 drivers (Seguridad=1, Usabilidad=2, Rendimiento=3, Disponibilidad=4, Compatibilidad=5), basada en impacto sobre datos y operación básica. Cibservabdi el mismo orden relativo para esos 5 atributos, y agrega 3 atributos que emergieron al construir el backend real (Mantenibilidad, Escalabilidad, Observabilidad), que no formaban parte del anteproyecto original porque no existía todavía un backend que mantener, escalar u observar. Disponibilidad sube de posición relativa aquí respecto a Docs/01 porque, a diferencia de cuando se escribió esa priorización (dependía solo de Firebase, externo), ahora hay infraestructura propia (Postgres) que el equipo administra directamente, y ya se vivió una caída real de esa infraestructura, siendo una evidencia que no existía al momento de la priorización original.

## Cómo se prioriza

- **Alta**: el atributo tiene un requisito no funcional formal asociado, evidencia de riesgo real ya encontrada (no hipotética), y su incumplimiento tiene consecuencia legal, de seguridad de datos personales, o de pérdida total de servicio.
- **Media**: tiene un RNF asociado o un driver de negocio claro, pero el riesgo real medido hasta ahora es bajo para el alcance actual (equipo pequeño, tráfico académico, no producción real).
- **Baja**: es deseable a futuro, pero el equipo tomó la decisión consciente de no invertir en él todavía dado el alcance (ver clasificaciones "Falso"/"Genérico" en el documento de escenarios).

## Matriz

| Atributo de calidad | Prioridad en Docs/01 §5.2 | Driver de negocio | Driver de calidad | Prioridad (esta matriz) | Justificación | Evidencia en el sistema real |
|---|---|---|---|---|---|---|
| **Seguridad** | 1 (RNF02) | Cumplimiento normativo | Seguridad | **Alta** | Ley 1581 de 2012 (RNF02) es un requisito legal, no opcional; ya se encontraron y verificaron riesgos reales concretos (IDOR mitigado, pero XSS y ausencia de rate limiting sin mitigar). Coincide con la prioridad 1 ya establecida. | bcrypt (costo 12), verificación de JWT/ID token de Firebase en cada request, protección IDOR probada con `curl` (403 real), consultas parametrizadas en las 4 capas de repositorios. |
| **Disponibilidad** | 4 (RNF03) | Confiabilidad del servicio | Seguridad (resiliencia) | **Alta (sube respecto a Docs/01)** | RNF03 exige ≥95% de disponibilidad; el equipo ya vivió una caída real (`postgres:latest` incompatible). Docs/01 lo priorizó en 4º lugar cuando la única dependencia era Firebase (externa); ahora que hay infraestructura propia que el equipo administra, un fallo aquí es responsabilidad del equipo, no de un tercero y eso justifica subir su prioridad. | `postgres:16-alpine` fijado tras el incidente; `healthcheck` en el `docker-compose`; `depends_on: condition: service_healthy`. |
| **Usabilidad** | 2 (RNF01) | Crecimiento de usuarios | — (condiciona a todos) | **Media-Alta (se mantiene cerca de Docs/01)** | RNF01 exige diseño para público de baja alfabetización digital; hay fricción real introducida por seguridad (contraseña mínima, verificación de auth) que compite con este atributo trade-off ya documentado. | Trade-off "Seguridad vs. Usabilidad" en `Docs/02`; decisión de mantener Firebase Auth (UX ya validada) en vez de un formulario propio con más fricción. |
| **Rendimiento** | 3 (RNF04) | Crecimiento de usuarios | Rendimiento | **Media** | RNF04 exige tiempos medibles, ya hay medición real (EXP-002: p95 = 1 ms, throughput ≈ 869 req/s); se mantiene media porque el volumen real está lejos de estresar el sistema. | Índices en `receta(id_categoria_rec)`, `receta(id_tipo_cocina)`, `inventario_usuario(id_usuario)`, `inventario_usuario(fecha_vencimiento)`; medición en `experimentos/EXP-002-listado-recetas/`. |
| **Compatibilidad** | 5 (RNF05) | Crecimiento de usuarios | — | **Baja (igual que Docs/01)** | Sin cambios: sigue siendo el atributo de menor impacto relativo dentro del alcance actual. | Verificado en navegadores probados (Docs/01); sin evidencia nueva que cambie su prioridad. |
| **Mantenibilidad** *(nuevo, no estaba en Docs/01)* | — | Reducción de costos | Escalabilidad | **Media-Alta** | No estaba en los drivers originales porque no existía backend propio que mantener. Emergió como prioridad real al construirlo: normalizar el modelo de datos (9+ tablas vs. array plano) reduce el costo de agregar features o corregir bugs.| Monolito modular por capas (`Docs/08-decision-estilo-arquitectonico.md`); separación de `ingrediente` (catálogo) e `inventario_usuario` (instancia), corrigiendo una violación de normalización real. |
| **Escalabilidad** *(nuevo, no estaba en Docs/01)* | — | Crecimiento de usuarios | Escalabilidad | **Baja (decisión consciente, no descuido)** | El equipo evaluó autoescalado/réplicas/Kubernetes y los clasificó como "Falso"/"sobredimensionado" para el alcance. Sobre-ingeniería para 2-3 personas en 8 semanas. Coincide con el criterio de `Docs/08` (elegir el estilo que exige menos infraestructura nueva). | `docker-compose.yml` con un solo contenedor `db` sin réplicas — decisión documentada. |
| **Observabilidad** *(nuevo, no estaba en Docs/01)* | — | Confiabilidad del servicio | Observabilidad | **Baja (gap real, no priorizado por alcance)** | El sistema real no tiene logging estructurado, métricas ni alertas. Hoy el único "registro" son los `console.error` del backend y el diagnóstico manual vía `docker compose logs`. Baja no porque no importe, sino porque no ha habido tiempo y no ha causado un incidente todavía. | Ausencia confirmada: no hay configuración de logging estructurado (ej. Winston/Pino) ni métricas (ej. Prometheus) en `backend/src/`. |

## Lectura de la matriz

Los dos atributos en Alta (Seguridad y Disponibilidad) son los únicos que ya tienen tanto un requisito formal (RNF) como un incidente o hallazgo real que demuestra que el riesgo no es hipotético lo que los distingue de Rendimiento, que sí tiene RNF pero cuya evidencia real (EXP-002) muestra holgura, no un problema. Mantenibilidad emergió como prioridad real al construir el backend, algo que el anteproyecto original no podía anticipar porque no existía todavía código que mantener. Escalabilidad y Observabilidad quedan en Baja por la misma razón documentada en los escenarios "Falso": El equipo decidió conscientemente no invertir ahí todavía dado el alcance real del proyecto.